version: "3.9"
services:
  app:
    build:
      context: .
      target: builder
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=development
      - DATABASE_HOSTNAME=database
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_LOGGING=true
      - DATABASE_PORT=5432
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    command: ["npm", "run", "start"]
  database:
    image: postgres:13.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
